name: buildpack-deps

permissions:
  pull-requests: write

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'scripts/docker/buildpack-deps/Dockerfile.emscripten'
      - 'scripts/docker/buildpack-deps/Dockerfile.ubuntu.clang.ossfuzz'
      - 'scripts/docker/buildpack-deps/Dockerfile.ubuntu2404'
      - 'scripts/docker/buildpack-deps/Dockerfile.ubuntu2404.clang'

jobs:
  buildpack-deps:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_REPOSITORY: solbuildpackpusher/solidity-buildpack-deps
      IMAGE_NAME: buildpack-deps

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image_variant: [emscripten, ubuntu.clang.ossfuzz, ubuntu2404, ubuntu2404.clang]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Upgrade ${{ env.IMAGE_NAME }}-${{ matrix.image_variant }}
        run: |
          echo ${DOCKERHUB_TOKEN} | docker login -u solbuildpackpusher --password-stdin
          scripts/ci/docker_upgrade.sh ${{ env.IMAGE_NAME }} ${{ matrix.image_variant }} ${{ env.DOCKER_REPOSITORY }}
          docker logout

      - name: comment PR
        if: "env.DOCKER_IMAGE"
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          message: "`${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_REPO_DIGEST }}`."
